import type { Metadata } from "next";
import NavBar from "./components/NavBar";
import { Provider } from "jotai";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='nl'>
			<body>
				<Provider>
					<NavBar />
					{children}
				</Provider>
				<Toaster />
			</body>
		</html>
	);
}
